import "./globals.css";
import { Inter } from "next/font/google";
// import authReducer from "../store";
// import { configureStore } from "@reduxjs/toolkit";
// import { Provider } from "react-redux";
// import {
// 	persistStore,
// 	persistReducer,
// 	FLUSH,
// 	REHYDRATE,
// 	PAUSE,
// 	PURGE,
// 	REGISTER,
// 	PERSIST,
// } from "redux-persist";
// import storage from "redux-persist/lib/storage";
// import { PersistGate } from "redux-persist/integration/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "ESM",
	description: "Generated by create next app",
};

// const persistConfig = { key: "root", storage, version: 1 };
// const persistedReducer = persistReducer(persistConfig, authReducer);
// const store = configureStore({
// 	reducer: persistedReducer,
// 	middleware: (getDefaultMiddleware) =>
// 		getDefaultMiddleware({
// 			serializableCheck: {
// 				ignoredActions: [FLUSH, REHYDRATE, PAUSE, PERSIST, PURGE, REGISTER],
// 			},
// 		}),
// });

export default function RootLayout({ children }) {
	return (
		<>
			{/* <Provider store={store}>
				<PersistGate loading={null} persistor={persistStore(store)}> */}
			<html id="main-html" lang="en" data-theme="forest">
				<body className={inter.className}>{children}</body>
			</html>
			{/* </PersistGate>
			</Provider> */}
		</>
	);
}
